---
title: "Neon colors may help some corals stage a comeback from bleaching"
description: This article is why the corals product neon colors ?
author: Lise 
  - name: 
    url: {}
date: 11-21-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

### source url 

https://www.sciencenews.org/article/corals-algae-neon-colors-bleaching-recovery-oceans
word count : 552

### vocabulary 
|Word from the text|Synonym/definition in English|French translation|
| --- | --- | --- |
|act as|syn: like|comme/en tant que|
|dwell|to live|habiter/deleuré|
|to struggle|to have difficult|avoir du mal|
|hues|colour|nuances/teintes|
|to shine|syn: to ligth|éclairer/diriger|
|uptick|increase|légère hausse|
|mild|syn: to lower|léger|
|to ramp up|intensity work|redoubler d'effort/accroitre|
|to plummet|syn: to fall|chuter|
|to bump up|syn: increase|augmenter|
|imblance|not equilibrium|désiquilibre|
|bounce|rebound|rebondir|
|to prompt|to take care yourself|se pomponner|
|vivildy|intensely|avec éclat|
|doom|dead|mort/perte|

|analysis|/     |
| --- | --- |
|Researchers?|Elena Bollati, Daniel Wangpraseurt and Jörg Wiedenmann|
|Published in? when (if mentioned)?|ScienceNews, May 29 2020|
|General topic|This article is about hues corals which change with the climate change.  Moreover, some wavelength can produce a certain effect on the corals colours with a pigment production. Certain neon colour is an imbalance nutriments chez corals.|
|Procedure/ what was examined|For to understand this changments. The researchers are working in labs. They realized a context like a increasing temperature in a aquarium. After several week, they observed that corals had bumped up their fluorescent.|
|Conclusions/ discovery|When certain the corals suffer a rise temperature they bump up their concentration fluorescent and change colors. Furthermore, while the high temperature the symbiosis with alguae no exist. But certain corals product more neaon color for to have a effect like a sunscreen.|
|Remaining questions|/|


