---
title: "My English Activity Log : MEAL"
author:
  - name: "___" 
date: "`r Sys.Date()`"
categories:
  - "English for Science"
  - "M.E.A.L."
output: distill::distill_article
preview: 
---

### My English activities 



- Sept. 30th: Since september, I have watched glee. I love this series because it's understanding and there is a lot songs. It's very entertaining ! 

- Oct. 14th : I bought a book in english. Your title is "Alice's adventures in wonderland" written by Lewis Carroll. I haven't really starting  because i don't have any times for to read. To all appearance the vocabulary look complex.

- Oct. 26th: I watched 2 episodes of "Our planet " on Netflix  (English with English subtitles). It's was very striking but also interesting. This documentary serie is splitting to suit to environment like forest, jungle, ocean,...

- Almost Oct. 31th: I watched "Transylvania hotel 1,2,3" (english with english subtitles) it's a halloween animation movie. My favorite movie among the third is the first because it's more funny than the others. 

- Dec. 4th: I watched Peter Pan 2010 (english with english subtitles) I loved to watch this film in english becauce it was my favourite movie when I was children. 

- Feb.7th to 12th: I watched all the "Hunger Games" ( english with english subtitles) it was special to heard the actors original voice. I like these movies because  for my part they denounce the poverty and the difference between the class. Like in the reality. 






