---
title: "How seaweed-munching crabs could help save coral reefs"
categories:
  - Articles
descriptio: This article is about crabs which can to save the corals grace to their alimentation
author:
  - name: Lise VE
    url: {}
date: 02-13-2021
preview: images/Maguimithrax_spinosissimus_male_dorsal_Florida_01.jpg
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



![Mithrax spinosissimus, par Adiël A. Klompmaker , Roger W. Portell, Aaron T. Klier, Vanessa Prueter, Alyssa L. Tucker - Klompmaker AA, Portell RW, Klier AT, Prueter V, Tucker AL. (2015) Spider crabs of the Western Atlantic with special reference to fossil and some modern Mithracidae. PeerJ 3:e1301 (https://dx.doi.org/10.7717/peerj.1301), CC BY 4.0](images/Maguimithrax_spinosissimus_male_dorsal_Florida_01.jpg)
### source url 
https://www.sciencedaily.com/releases/2020/12/201210112120.htm
words : 676

### vocabulary 
|Word from the text|Synonym/definition in English|French translation|
| --- | --- | --- |
|Seaweed|Sea plants|Algues|
|The under-appreciated|not appreciated|sous-apprécier|
|Wondered|Be curious|Se demander| 
|Split|Cause to break|Couper| 
|Scrubbed|Cleaned|Frotter|
|Dent|Dent|Renfoncement| 
|Tool|Method|Outil| 
|Onto|On top|Sur| 
|The mind-boggling|Informal|Impressionnant| 
|Fringes|Bangs|Frange| 

### analysis
|analysis|/     |
| --- | --- |
|Researchers?|Mark Butler, Jason Spadaro|
|Published in? when (if mentioned)?|ScienceDaily,December 10 2020|
|General topic|This article speak about crabs use for to eat the alguae (or seaweed) which cover the coral reef. This alguae avoid the correct coral development.Grace to herbivore crabs there are a decrease to less than 50% seaweed on the reef. |
|Procedure/ what was examined|Unfortunately, the Caribbean crabs aren't from Florida, so researchers have been implemented a farming. Then, they put the crabs on the reef which are 80% covered by alguae. They get a final result where the reef was only covered with 20% alguae.|
|Conclusions/ discovery|Other animals can be used for the coral development, in this case it's caribean crabs which help the corals to correctly grow because they feed on the alguae which cover the coral reef avoid their growth.|
|Remaining questions|/|

